version: '3.9'

services:
  db:
    image: mysql:8.0.26
    restart: always
    environment:
      MYSQL_DATABASE: 'customer_db'
      MYSQL_USER: 'customer_user'
      MYSQL_PASSWORD: 'customer_pass'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql

volumes:
  my-db:
