server:
  port: 8080
  error:
    include-binding-errors: always
    include-message: always
    include-stacktrace: never

application:
  title: poc-customer
  version: 1.0.0

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  paths-to-match: /**
  packages-to-scan: com.nobrega.poc.customer
  show-actuator: true
  swagger-ui:
    operations-sorter: alpha
    disable-swagger-default-url: true
    path: /swagger-ui.html

spring:
  kafka:
    bootstrap-servers: localhost:9092
    key-serializer: org.apache.kafka.common.serialization.StringSerializer
    value-serializer: org.apache.kafka.common.serialization.StringSerializer
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DB:customer_db}?autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
    username: ${MYSQL_USER:customer_user}
    password: ${MYSQL_PASSWORD:customer_pass}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate.ddl-auto: validate
    open-in-view: true
    show-sql: true
    properties:
      hibernate.format_sql: true


api.security.token.secret: ${JWT_SECRET:12345678}

topic:
  create-customer: topic.create.customer
