#Workflow name
name: CI/CD Pipeline
on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
jobs:
  unit-tests:
    name: Unit Tests
    runs-on: self-hosted
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'

      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.5
        with:
          maven-version: 3.8.5

      - name: Compile and unit tests
        run: mvn clean install

      - name: Publish Unit Test Report
        uses: mikepenz/action-junit-report@v3
        if: always()
        with:
          check_name: 'Unit Tests Report'
          report_paths: '**/target/surefire-reports/TEST-*.xml'
