#Workflow name
name: CI/CD Pipeline

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build
        run: mvn --batch-mode -DskipTests package

      - name: Test
        run: mvn --batch-mode -Dmaven.test.failure.ignore=true test

      - name: Publish Unit Test Report
        uses: mikepenz/action-junit-report@v3
        if: always()
        with:
          check_name: Unit Test Report
          report_paths: '**/target/surefire-reports/TEST-*.xml'
      # generates coverage-report.md and publishes as checkrun
